---
# This file deploys all resources necessary for a working, single-node ElasticSearch
# service to sink fluentd events.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-data-pvc
spec:
  storageClassName: managed-nfs-storage
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: kube-logging
  name: elasticsearch-deployment
  labels:
    app: es-logging
spec:
  selector:
    matchLabels:
      app: es-logging
  replicas: 1
  template:
    metadata:
      namespace: kube-logging
      labels:
        app: es-logging
    spec:
      volumes:
        - name: data-pv
          persistentVolumeClaim:
            claimName: es-data-pvc
      containers:
        - name: elasticsearch
          image: elasticsearch:7.14.2
          resources:
            limits:
              cpu: 2000m
            requests:
              cpu: 500m
              memory: 256Mi
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms256m -Xmx256m"
          volumeMounts:
            - mountPath: "/usr/share/elasticsearch/data"
              name: data-pv
      imagePullSecrets:
        - name: dockerhub
---
kind: Service
apiVersion: v1
metadata:
  namespace: kube-logging
  name: es-logging-svc
spec:
  type: NodePort
  selector:
    app: es-logging
  ports:
    - port: 9200
      protocol: TCP
      targetPort: 9200
