---
# Create a service to expose the ElasticSearch deployment on the service network at TCP/9200.
# For convenience, the service also exposes a node port to permit smoke testing or external
# access to the ES server.
kind: Service
apiVersion: v1
metadata:
  namespace: kube-logging
  name: es-logging-svc
spec:
  selector:
    app: es-logging
  ports:
    - port: 9200
      protocol: TCP
      targetPort: 9200
