---
# Create a single-node ElasticSearch "cluster" to serve as a sink for fluentd.
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: kube-logging
  name: elasticsearch-deployment
  labels:
    app: es-logging
spec:
  selector:
    matchLabels:
      app: es-logging
  replicas: 1
  template:
    metadata:
      namespace: kube-logging
      labels:
        app: es-logging
    spec:
      volumes:
        - name: data-pv
          persistentVolumeClaim:
            claimName: es-data-pvc
      containers:
        - name: elasticsearch
          image: elasticsearch:7.14.2
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 500m
              memory: 256Mi
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms128m -Xmx128m"
          volumeMounts:
            - mountPath: "/usr/share/elasticsearch/data"
              name: data-pv
      imagePullSecrets:
        - name: dockerhub
