---
# Deploy Kibana to the kube-logging namespace and connect it to the ElasticSearch service.
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: kube-logging
  name: kibana-deployment
  labels:
    app: kibana-logging
spec:
  selector:
    matchLabels:
      app: kibana-logging
  replicas: 1
  template:
    metadata:
      namespace: kube-logging
      labels:
        app: kibana-logging
    spec:
      containers:
        - name: kibana
          image: kibana:7.14.2
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 500m
              memory: 256Mi
          ports:
            - containerPort: 5601
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://es-logging-svc:9200"
