---
# Deploys all resources necessary to host Kibana, a web application for viewing aggregated logs.
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: kube-logging
  name: kibana-deployment
  labels:
    app: kibana-logging
spec:
  selector:
    matchLabels:
      app: kibana-logging
  replicas: 1
  template:
    metadata:
      namespace: kube-logging
      labels:
        app: kibana-logging
    spec:
      containers:
        - name: kibana
          image: kibana:7.14.2
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 500m
              memory: 256Mi
          ports:
            - containerPort: 5601
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "http://es-logging-svc:9200"
---
kind: Service
apiVersion: v1
metadata:
  namespace: kube-logging
  name: kibana-logging-svc
spec:
  selector:
    app: kibana-logging
  ports:
    - port: 5601
      protocol: TCP
      targetPort: 5601
      name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana-ingress
  namespace: kube-logging
spec:
  rules:
    - host: kibana.lab
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: kibana-logging-svc
                port:
                  number: 5601
