---
# Create a single-node ElasticSearch "cluster" to serve as a sink for fluentd.
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: kube-registry
  name: registry-deployment
  labels:
    app: registry
spec:
  selector:
    matchLabels:
      app: registry
  replicas: 1
  template:
    metadata:
      namespace: kube-registry
      labels:
        app: registry
    spec:
      containers:
        - name: docker-registry
          image: registry:2
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
            requests:
              cpu: 500m
              memory: 256Mi
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /etc/docker/registry
              name: config-volume
            - mountPath: /var/lib/registry
              name: registry-data-volume
      #          env:
      #            - name: REGISTRY_STORAGE_S3_ACCESSKEY
      #              valueFrom:
      #                secretKeyRef:
      #                  name: s3-creds
      #                  key: access_key
      #            - name: REGISTRY_STORAGE_S3_SECRETKEY
      #              valueFrom:
      #                secretKeyRef:
      #                  name: s3-creds
      #                  key: secret_key
      volumes:
        - name: registry-data-volume
          persistentVolumeClaim:
            claimName: registry-data-pvc
        - name: config-volume
          configMap:
            name: registry-config
      imagePullSecrets:
        - name: dockerhub
