---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster-addr-map
data:
  script: |
    # Capture the addresses of all known cluster members immediately before 
    # shutdown.
    source "$REDIS_SCRIPT_DIR/cluster-common.sh"

    FQDN="$(lookup_node_ip $POD_NAME)"
    update_last_known_address "$FQDN"
