kind: Deployment
apiVersion: apps/v1
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  template:
    spec:
      containers:
        - name: elasticsearch
          resources:
            limits:
              cpu: 1500m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 256Mi
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms256m -Xmx256m"
