apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis
commonLabels:
  app: redis
resources:
  - redis-cluster-common.yml
  - redis-cluster-init.yml
  - redis-cluster-fix-address.yml
  - redis-config.yml
  - shared-storage.yml
  - service.yml
  - statefulset.yml
