---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster-common
data:
  script: |
    # Given a node name, create a FQDN that can be resolved within the service 
    # network.
    create_node_FQDN() {
      echo "$1.redis-svc.$POD_NAMESPACE.svc.cluster.local"
    }

    # Create an array of cluster member FQDNs. Values are added to an empty array that
    # must be passed as the first argument.    
    list_cluster_members() {
      local -n members=$1
      for ((i=0; i<$2; i++))
      do
        members[i]="$(create_node_FQDN redis-$i)"
      done
    }

    # Test a cluster member to see if it's online.
    is_node_online() {
      if [[ $(redis-cli -h $1 -p 6379 ping) == "PONG" ]]; then
        echo "yes"
      else
        echo "no"
      fi
    }

    # Wait for a set of Redis nodes to be ready before returning control to the caller.
    # The set must be passed as an array in first argument.
    wait_for_cluster_ready() {
      local -n members=$1
      for i in "${members[@]}"
      do
          while [[ $(is_node_online $i) == "no" ]]
          do
              echo "Waiting for redis server $i to come online."
              sleep 5
          done  
          echo "Redis server $i is online."
      done
    }

    # Retrieve a cluster member's IP address.
    lookup_node_ip() {
      local member_ip=($(getent hosts $1)) 
      echo ${member_ip[0]}
    }

    # Iterate through a provided array of cluster nodes and write each one's
    # name and current IP address to a file.
    update_last_known_address() {
      local ip=$(lookup_node_ip $1)    
      local replacement="$1 $ip"

      if [ -f "$REDIS_CLUSTER_STATE_DIR/last_known_address.txt" ]; then
        if cat $REDIS_CLUSTER_STATE_DIR/last_known_address.txt | grep -e "$1"; then
          # We have a record of this node; update the file with the current address.          
          echo "Updating existing entry with '$replacement'"
          sed -i "s/$1 .*/$replacement/" $REDIS_CLUSTER_STATE_DIR/last_known_address.txt
        else
          # We don't know about this node yet; add it to the file.
          echo "Adding '$replacement' to file."
          echo "$replacement" >> "$REDIS_CLUSTER_STATE_DIR/last_known_address.txt"
        fi
      else
        # Looks like this is the first node; create the file.
        echo "Creating new file."
        echo "$replacement" >> "$REDIS_CLUSTER_STATE_DIR/last_known_address.txt"
      fi   
    }

    # Given an FQDN, search the address map for the node's IP and return it to
    # the caller.
    find_last_known_address() {
      local address=""

      while IFS= read -r line
      do 
        local record=($line)
        if [[ "${record[0]}" == "$1" ]]; then
          address="${record[1]}"
          break
        fi
      done < $REDIS_CLUSTER_STATE_DIR/last_known_address.txt

      echo "$address"
    }
