# Headless service required to manage the stateful set's network namespace.
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      name: redis
    - port: 16379
      name: cluster-bus
  clusterIP: None
  selector:
    app: redis
