---
# Create an nfs-backed persistent volume claim to hold ElasticSearch indexes. This
# PVC assumes the following:
# * The Kubernetes NFS Subdir External Provisioner (see https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner)
#   is installed in the cluster
# * The NFS provisioner will provision an NFS v4 mount. While NFS technically isn't support by
#   ElasticSearch it will work with NFS v4 only.
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-data
spec:
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 25Gi
  accessModes:
    - ReadWriteOnce
